services: 



  inventoryapiauth:
    build:
      context: .
      dockerfile: /InventoryAPIAuth/Dockerfile  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:5002"
   
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge

