services: 
  sqlserver: 
    image: mcr.microsoft.com/mssql/server:2022-latest 
    container_name: sqlserver 
    environment: 
      - MSSQL_SA_PASSWORD=RedArbor*2024 
      - ACCEPT_EULA=Y 
    ports:
      - "1433:1433" 
    volumes:
      - ./data:/var/opt/mssql/data

  inventoryapiwrite:
    build:
      context: .
      dockerfile: /InventoryAPIWrite/Dockerfile  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=InventoryDB;User=sa;Password=RedArbor*2024;TrustServerCertificate=True;
    ports:
      - "5001:80"
    depends_on:
      - sqlserver
    networks:
      - inventory-network

  inventoryapiread:
    build:
      context: .
      dockerfile: /InventoryAPIRead/Dockerfile  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=InventoryDB;User=sa;Password=RedArbor*2024;TrustServerCertificate=True;
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - inventory-network

  inventoryapiauth:
    build:
      context: .
      dockerfile: /InventoryAPIAuth/Dockerfile  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"
    depends_on:
      - sqlserver
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge

