services: 
  sqlserver: 
    image: mcr.microsoft.com/mssql/server:2022-latest 
    container_name: sqlserver 
    environment: 
      - MSSQL_SA_PASSWORD=RedArbor*2024 
      - ACCEPT_EULA=Y 
    ports:
      - "1433:1433" 
    volumes:
      - ./data:/var/opt/mssql/data
